[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "mjo"
version = "0.0.1"
description = "Deep learning models for MJO forecasting"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    {name = "Khalil Virji", email = "kvirji@uci.edu"},
]
classifiers = [
    "Programming Language :: Python :: 3",
]

[project.urls]
Homepage = "https://github.com/khalilv/mjo-predict"

[tool.setuptools.packages.find]
where = ["src"]
