name: mjo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - xarray
  - matplotlib
  - scipy
  - pillow
  - netcdf4
  - hdf5
  - cftime
  - numba
  - shapely
  - pyproj
  - basemap
  - proj
  - cartopy
  - dask
  - distributed
  - tornado
  - pytorch
  - torchvision
  - torchaudio
  - typing_extensions
  - pyyaml
  - zarr
  - xesmf
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.3
      - aiosignal==1.3.1
      - alembic==1.14.1
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.2
      - attrs==22.2.0
      - axial-attention==0.6.1
      - bottle==0.13.3
      - cachetools==5.3.0
      - cdsapi==0.7.5
      - colorlog==6.9.0
      - contourpy==1.1.1
      - datapi==0.3.0
      - docstring-parser==0.15
      - einops==0.6.0
      - exceptiongroup==1.2.2
      - fairscale==0.4.13
      - filelock==3.9.0
      - fire==0.5.0
      - fonttools==4.55.0
      - frozenlist==1.3.3
      - google-auth==2.16.0
      - google-auth-oauthlib==0.4.6
      - greenlet==3.1.1
      - grpcio==1.52.0
      - huggingface-hub==0.12.0
      - importlib-resources==5.10.2
      - iniconfig==2.1.0
      - joblib==1.4.2
      - jsonargparse==4.34.1
      - kiwisolver==1.4.7
      - lightning==2.3.3
      - lightning-lite==1.8.6
      - lightning-utilities==0.11.9
      - mako==1.3.10
      - markdown==3.4.1
      - markdown-it-py==2.2.0
      - matplotlib==3.7.1
      - mdurl==0.1.2
      - multidict==6.0.4
      - multiurl==0.3.5
      - narwhals==1.41.0
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - optuna==4.3.0
      - optuna-dashboard==0.18.0
      - optuna-integration==4.3.0
      - plotly==6.1.2
      - pluggy==1.5.0
      - protobuf==3.20.3
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygments==2.18.0
      - pytest==8.3.5
      - pytest-json-report==1.5.0
      - pytest-metadata==3.1.1
      - pytorch-lightning==2.4.0
      - requests-oauthlib==1.3.1
      - rich==13.3.5
      - rsa==4.9
      - scikit-learn==1.3.2
      - sqlalchemy==2.0.41
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.2.0
      - threadpoolctl==3.5.0
      - timm==0.6.12
      - tomli==2.2.1
      - torchmetrics==0.11.1
      - tqdm==4.64.1
      - typeshed-client==2.2.0
      - werkzeug==2.2.2
      - yarl==1.8.2
