seed_everything: 42

# ---------------------------- TRAINER -------------------------------------------
trainer:
  default_root_dir: /Users/kvirji/Documents/mjo-predict/exps/TSMixer/historical_plus_dates/hist_10d_predict_60d
  precision: 32

  devices: 1
  num_nodes: 1
  accelerator: mps
  strategy: auto

  min_epochs: 1
  max_epochs: 250
  enable_progress_bar: true

  sync_batchnorm: false
  enable_checkpointing: true

  gradient_clip_val: 1.0

  fast_dev_run: false

  logger:
    class_path: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: ${trainer.default_root_dir}/logs
      name: null
      version: null
      log_graph: false
      default_hp_metric: true
      prefix: ""

  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"

    - class_path: mjo.utils.callbacks.GradientMonitor
      init_args:
        log_every_n_steps: 50

    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: "${trainer.default_root_dir}/checkpoints"
        monitor: "val/mse_norm"
        mode: "min"
        save_top_k: 1
        save_last: true
        verbose: false
        filename: "epoch_{epoch:03d}"
        auto_insert_metric_name: false

    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: "val/mse_norm"
        mode: "min"
        patience: 10
        min_delta: 0.

    - class_path: pytorch_lightning.callbacks.RichModelSummary
      init_args:
        max_depth: -1

    - class_path: pytorch_lightning.callbacks.RichProgressBar

# ---------------------------- MODEL -------------------------------------------
model:
  pretrained_path: ""
  past_cov_dim: 0
  future_cov_dim: 3
  static_cov_dim: 0
  nr_params: 1
  hidden_size: 32
  ff_size: 256
  num_blocks: 12
  activation: "ReLU"
  dropout: 0.8
  norm_type: "TimeBatchNorm2d"
  normalize_before: true
  lr: 7.5e-5
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 5e-4
  warmup_steps: 1000
  max_steps: 50000
  save_outputs: true

# ---------------------------- DATA -------------------------------------------
data:
  root_dir: /Users/kvirji/Documents/mjo-predict/DATA/MJO/preprocessed/reference_period_1979-09-07_to_2001-12-31
  in_variables:
    - "RMM1"
    - "RMM2"
    - "amplitude"
  out_variables:
    - "RMM1"
    - "RMM2"
  predictions: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60]
  history: [-10,-9,-8,-7,-6,-5,-4,-3,-2,-1]
  filter_mjo_events: true
  normalize_data: true
  max_buffer_size: 10000
  batch_size: 128
  num_workers: 0
  pin_memory: false
